databases:
  - name: furnitureshop
    databaseName: furnitureshop
    user: furnitureshop

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn furnitureshop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: furnitureshop
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4